### ISSUE TITLE
Feature request (maybe?)

### ISSUE THREAD

**Issue by jlpellicer** [doug-martin/goqu#101]
I'm trying out your package, which looks pretty good, except that I hit a bump, maybe I'm getting it wrong or it may be something worth.

My problem is the `select` part, my selects are usually extremely detailed and something include things like `coalesce(to_char("Payment"."paidDate", 'YYYY-MM-DD HH24:MI:SS'), '') as "paidDate"`.

I wouldn't want `goqu` to do this for me, I'm fine with that so, here's the idea, how about if we could somehow provide the `select` to `goku`? That way I could make my select as detailed or complex and use `goku` to build the `where`

Does it make any sense?

**Comment by doug-martin** [comment]
I think  goqu.L should suit your needs, it  allows you to provide raw SQL instead of using the dsl in places. 

Let me know if that works.

**Comment by doug-martin** [comment]
Here is a link to the docs, https://godoc.org/github.com/doug-martin/goqu#L

**Comment by jlpellicer** [comment]
Thanks, I'll look into it
