### ISSUE TITLE
How to use raw statements as property values?

### ISSUE THREAD

**Issue by hookover** [doug-martin/goqu#102]
eg:
update tb set a=a+1,b=(case when z>0 then 1 else 0 end) where id=(select max(id) from tb)
insert into tb(id,score) values(1, case when x>0 then 1 else 0 end)

How to generate such a SQL？

**Comment by chen56** [comment]
goqu.v7: 

database.Exec("update tb set a=a+1,b=(case when z>0 then 1 else 0 end) where id=(select max(id) from tb)")

or goqu.L()

```go
	fmt.Println(dialect.From("tb").
		Where(goqu.L("id=(select max(id) from tb)")).
		ToUpdateSQL(goqu.Record{"a": goqu.L("a+1"), "b": goqu.L("(case when z>0 then 1 else 0 end)")}))
	fmt.Println(dialect.From("tb").
		ToInsertSQL(goqu.Record{"id": 1, "score": goqu.L("case when x>0 then 1 else 0 end")}))
```

**Comment by hookover** [comment]
> goqu.v7:
> 
> database.Exec("update tb set a=a+1,b=(case when z>0 then 1 else 0 end) where id=(select max(id) from tb)")
> 
> or goqu.L()
> 
> ```go
> 	dialect := goqu.Dialect("mysql")
> 	fmt.Println(dialect.From("tb").
> 		Where(goqu.L("id=(select max(id) from tb)")).
> 		ToUpdateSQL(goqu.Record{"a": goqu.L("a+1"), "b": goqu.L("(case when z>0 then 1 else 0 end)")}))
> 	fmt.Println(dialect.From("tb").
> 		ToInsertSQL(goqu.Record{"id": 1, "score": goqu.L("case when x>0 then 1 else 0 end")}))
> ```

谢谢
