### ISSUE TITLE
Directly selecting values from struct

### ISSUE THREAD

**Issue by ssttevee** [doug-martin/goqu#104]
Given the following struct

```go
type Person struct {
	Name string `db:"name"`
	Age int `db:"age"`
}

p := Person{
	Name: "Jon",
	Age: 30,
}
```

There doesn't seem to be a quick way to directly select all of the data from a struct:

```sql
SELECT 'Jon' AS "name", 30 AS "age"
```

Similar to the way it is interpreted in `Dataset.Insert()`:

```go
goqu.From("table").Insert(&p)
// INSERT INTO "table" ("name", "age") VALUES ("Jon", 30)
```

The current behaviour is:

```go
goqu.From().Select(&p) // SELECT "name", "age"
```
and
```go
goqu.From(&p) // SELECT * FROM "name", "age"
```

The best way I can come up with currently, is something like this:

```go
goqu.From().Select(
	goqu.L("?", p.Name).As("name"),
	goqu.L("?", p.Age).As("age"),
) // SELECT 'Jon' AS "name", 30 AS "age"
```

I'd like to propose a way to more easily build such a query.

I think there should be a new function, perhaps `goqu.V`, for explicitly stating that I want to use the value as a literal.

```go
goqu.From().Select(
	goqu.V("Jon").As("name"),
	goqu.V(30).As("age"),
) // SELECT 'Jon' AS "name", 30 AS "age"

goqu.From().Select(goqu.V(p)) // SELECT 'Jon' AS "name", 30 AS "age"

goqu.From().Select(goqu.V(p).As("person")) // SELECT ('Jon', 30) AS "person"
```

I'm not sure about the interactions with other expressions, or other databases, esp. the tuple syntax. It works in postgres though.

**Comment by doug-martin** [comment]
I added this in `v8.0.1` #113.  It just an alias for `goqu.L("?", val)`. Ill close this once I release the new version.
