### ISSUE TITLE
String methods on I(), Col(), etc

### ISSUE THREAD

**Issue by leebenson** [doug-martin/goqu#109]
Sometimes it's convenient to be able to grab a quick string for calls to `I()` etc, which can then be interpolated inside of a `L()` when it's necessary to use non-supported operators or re-order the expression.

Attaching a `.String()` method to get those fragments would be really useful.

**Comment by doug-martin** [comment]
@leebenson we could add a string method, could you provide a couple of examples to demonstrating how you might use it? I'd like to make sure I understand what you are asking.

You could also issue a PR with the change, tests and examples which may be quicker. Im currently in the middle of changing a couple of things to address some of the feature requests around inserts and updates.

**Comment by leebenson** [comment]
I think the main benefit would be escaping composable identifiers in literals that use non-standard operators, or where the order of where the identifier name appears isn't the usual `<ident> <operator> <expression>` pattern.

For example, I have the following literal that uses Postgres' `@>` 'contains' operator with an array (the `placeholders()` func just returns `?` x number of times, separated by commas, and `exc...` contains the params to explode):

```go
goqu.L(
  fmt.Sprintf(`NOT "%s" @> ARRAY[%s] `, c.Column, placeholders(excLen)),
  exc...,
)
```

I'm currently just wrapping the column in `""`, but that's not correct; if I passed in a `T(...).Col(...)`, it'd have quotes wrapping the whole lot rather than the individual parts.

Allowing `T("A").Col("B").String()` to return `"A"."B"` would make embedding this identifier in a literal composable and safer.

**Comment by doug-martin** [comment]
@leebenson I tried your example locally with a slight modification, I changed the %s for the c.Column to a `?` so it will be interpolated using the dialect, and it looks like it does what you want, but i could still be missing something.

```go
sql, _, _ = goqu.From("test").
	Select(goqu.L(
		fmt.Sprintf("NOT ? @> ARRAY[%s]", "?, ?, ?"),
		goqu.T("test").Col("col"),
		"a",
		"b",
		"c",
	)).ToSQL()
fmt.Println(sql)
```
Output:
```
SELECT NOT "test"."col" @> ARRAY['a', 'b', 'c'] FROM "test"
```

**Comment by leebenson** [comment]
Perfect! I didn't realise placeholders could be used with `exp.IdentifierExpression`s. This is great!
