### ISSUE TITLE
How to write subquery for mysql?

### ISSUE THREAD

**Issue by dtelyukh** [doug-martin/goqu#112]
I need this:
`SELECT * FROM table WHERE something = (SELECT something FROM table WHERE id = 1)`

I tried such code (ds builds earlier with mysql dialect and works correct for other queries):
```
	subds := goqu.From("table").Select("something").Where(goqu.I("id").Eq(1))
	ds = ds.Where(goqu.Ex{
		"id": goqu.Op{"eq": subds},
	})
```

which generated 
`SELECT * FROM "table" WHERE ("something" IN (SELECT "id" FROM "table" WHERE ("id" = 1)))`

That query doesn't work, because it has quotes.

**Comment by doug-martin** [comment]
Hi @dtelyukh you need to specify the dialect you want to use. Take a look at https://github.com/doug-martin/goqu/blob/master/docs/dialect.md#mysql

**Comment by dtelyukh** [comment]
Thank you! I thought at the morning that I didn't specify dialect to the subquery.
