### ISSUE TITLE
Bug in `createColumnMap`

### ISSUE THREAD

**Issue by efureev** [doug-martin/goqu#115]
```
type DeepPermission struct {
		IDStr string `json:"id"`
		Sep   string `json:"sep"`
	}

	type Permission struct {
		DeepPermission

		IDStr       string    `json:"id" db:"id"`
		Name        string    `json:"name" db:"name"`
		Description string    `json:"description" db:"description"`
		CreatedAt   time.Time `json:"-"`
	}

	p := &Permission{
		Name:        `app:create`,
		IDStr:       `Create a new App`,
		Description: `Description Create a new App`,
	}

sql, arg, err := r.db.Insert(`rbac_permissions`).
		Returning(goqu.C(`id`)).
		Rows(p).
		ToSQL()
```
1. with SetColumnRenameFunction == `-` 
```
goqu.SetColumnRenameFunction(func(v string) string {
	return "-"
})
...
// sql = "INSERT INTO "rbac_permissions" ("-", "description", "id", "name") VALUES ('0001-01-01T00:00:00Z', 'Description Create a new App', 'Create a new App', 'app:create')"
```
2. with SetColumnRenameFunction == `` 
```
goqu.SetColumnRenameFunction(func(v string) string {
	return ""
})
...
// sql =  "INSERT INTO "rbac_permissions" (, "description", "id", "name") VALUES ('0001-01-01T00:00:00Z', 'Description Create a new App', 'Create a new App', 'app:create')"
```

3. without SetColumnRenameFunction
```
// sql =  "INSERT INTO "rbac_permissions" ("createdat", "description", "id", "idstr", "name", "sep") VALUES ('0001-01-01T00:00:00Z', 'Description Create a new App', 'Create a new App', '', 'app:create', '')"
```

In steps above expects follow sql:
`INSERT INTO "rbac_permissions" ("description", "id", "name") VALUES ('Description Create a new App', 'Create a new App', 'app:create')`

 Or am I wrong?

**Comment by doug-martin** [comment]
The `SetColumnRenameFunction` will be for any column that doesnt have a db tag. It works just like the `json` tag where you need to explicitly ignore the field for it not to be used. The `SetColumnRename` function is used to transform column names that dont have a `db` tag.

In the first example its working as expected, goqu doesnt try to interpret what you transformed the field name to, instead it uses it as is.

The second example is an interesting one in that you returned an empty string and it generated the `(,` That should probably be an error when creating the SQL for an empty identifier. 

In the third example it is also working as expected, if you want to ignore the `CreatedAt` column it should be changed to:

```go
type Permission struct {
	DeepPermission

	IDStr       string    `json:"id" db:"id"`
	Name        string    `json:"name" db:"name"`
	Description string    `json:"description" db:"description"`
	CreatedAt   time.Time `json:"-" db:"-"`
}
```
