### ISSUE TITLE
Reflect error 2

### ISSUE THREAD

**Issue by efureev** [doug-martin/goqu#118]
```
// struct is in a custom package
type SimpleRole struct {
	sync.RWMutex
	permissions []string
}

// .....

type Role struct {
	*SimpleRole

	Id        string    `json:"id" db:"id" goqu:"skipinsert"`
	Key       string    `json:"key" db:"key"`
	Name      string    `json:"name" db:"name"`
	CreatedAt time.Time `json:"-" db:"created_at" goqu:"skipinsert"`
}
```

## Error 1
panic: reflect: indirection through nil pointer to embedded struct
```
rUser := &Role{
		Key:  `user`,
		Name: `User role`,
	}

// The Error appears here:
sql, arg, err := database.Insert(`rbac_roles`).
		Returning(goqu.C(`id`)).
		Rows(rUser).
		ToSQL()

```
## Error 2
reflect.Value.Interface: cannot return value obtained from unexported field or method.
```
rUser := &Role{
		Key:  `user`,
		Name: `User role`,
		SimpleRole: &SimpleRole{
			IDStr: ``,
		},
	}

// The Error appears here:
sql, arg, err := database.Insert(`rbac_roles`).
		Returning(goqu.C(`id`)).
		Rows(rUser).
		ToSQL()

```
and :  
(reflect.Value.Interface: cannot return value obtained from unexported field or method)
```
type Role struct {
	sync.RWMutex `db:"-"`
	Id        string    `json:"id" db:"id"`
}

rUser := Role{
	Id:  `user`,
}
sql, arg, err := database.Insert(`rbac_roles`).Rows(rUser).ToSQL()
```

**Comment by doug-martin** [comment]
I've done some more investigation into this and I found a couple of issues that will be addressed in the next release. I'm currently working on fixes.

1. When creating the columnMap `goqu` is not filtering out unexported fields that cant be set, in the next release those will be filtered.
2. I've added support for ignoring embedded structs.
```go
// struct is in a custom package
type SimpleRole struct {
    sync.RWMutex
    permissions []string
}

// .....

type Role struct {
   *SimpleRole `db:"-"`
    Id        string    `json:"id" db:"id" goqu:"skipinsert"`
    Key       string    `json:"key" db:"key"`
    Name      string    `json:"name" db:"name"`
    CreatedAt time.Time `json:"-" db:"created_at" goqu:"skipinsert"`
}
```
3. When building the insert or update statements that access the field values Im using the column map to look up fields however `goqu` was not accounting for the fact that a field may be part of an embedded pointer that may be nil.

Thank you for submitting this issue it pointed out quite use cases that should be handled. I hope to have a fix out in the next day or so.
