### ISSUE TITLE
Add .WhereFromSql(clause string) method

### ISSUE THREAD

**Issue by dustinsmith1024** [doug-martin/goqu#12]
What would you think about a simple `WhereFromSQL()` method that takes a string?

```go
var invoices []*Invoice
DB.From("invoice").WhereFromSQL("status = 'NEW'").ScanStructs(&invoices)
```

Might not be much better than doing it with ScanStruct.
```go
where := "status = 'NEW'"
err := wfc.db.ScanStructs(&loans, "select * from loan where "+where+";")
```

It would help make reusable functions where we can just pass around a string vs having to try and build and accept the different kinds of goqu Expressions.

**Comment by TechnotronicOz** [comment]
@dustinsmith1024 You could do something like

```golang
var invoices []*Invoice
DB.
    From("invoice").
    Where(goqu.Ex{"status": "'NEW'"}).
    ScanStructs(&invoices)
```

**Comment by dustinsmith1024** [comment]
I didn't know goqu.L() existed, that could work for what I want.
