### ISSUE TITLE
using goqu to create prepared statements

### ISSUE THREAD

**Issue by ldelossa** [doug-martin/goqu#127]
Hello there,

I am attempting to use Goqu to create a large set of queries. These queries will be selected based on the context of a request. I would also like to "prepare" these queries with the standard `sql/db` module. For me to do this I need Goqu to actually produce SQL statements with the bind variable placeholders. For example `SELECT * FROM table WHERE value = $1`. 
Is this currently possible or will '$1' always be quoted in the resulting Query?

**Comment by doug-martin** [comment]
Goqu will handle that for you if you use the correct dialect, `postgres` is currently the only dialect that supports placeholders in that format.

Take a look at:

https://github.com/doug-martin/goqu/blob/master/docs/dialect.md
https://github.com/doug-martin/goqu/blob/master/docs/interpolation.md 

Hope this helps.
