### ISSUE TITLE
How to form an update query with increment 

### ISSUE THREAD

**Issue by kunal-plivo** [doug-martin/goqu#129]
I want to form the below query
`UPDATE FROM tableA SET a = a + 1 WHERE b = "something"`
I want a workaround to somehow set `a = a+1`

Statement so far:
```
_, _ = db.From("tableA").
		Where(goqu.Ex{"b": "something"}).
		Update(goqu.Record{"a": "\"a\"+1"}).Exec()
```

The query forming from this is below:
`UPDATE "tableA" SET "a"='"a"+1' WHERE ("b" = 'something')`

**Comment by doug-martin** [comment]
Hi @kunal-plivo take a look at the sql literal documentation https://github.com/doug-martin/goqu/blob/master/docs/expressions.md#L 

Here is an example to solve your problem above.

```go
sql, args, _ = goqu.Update("tableA").
	Where(goqu.Ex{"b": "something"}).
	Set(goqu.Record{
    // use goqu.L to create a custom sql fragment.
		"a": goqu.L("? + ?", goqu.C("a"), 1),
	}).ToSQL()
fmt.Println(sql, args)
```

Output:
```
UPDATE "tableA" SET "a"="a" + 1 WHERE ("b" = 'something') []
```
