### ISSUE TITLE
Dialect not honored for Insert

### ISSUE THREAD

**Issue by marshallmcmullen** [doug-martin/goqu#130]
First, I want to thank you for `goqu`. It's fantastic and I'm loving it so far!

I think I found an issue with `Insert` not honoring the dialect setting for the placeholders. The simplest test to exhibit this is the following:

```
func TestInsertDialect(t *testing.T) {

    dialect := goqu.Dialect("postgres")

    var value1, value2 int 

    insertDataset := dialect.Insert("foo").Prepared(true).Rows(goqu.Record{
        "value1": value1,
        "value2": value2,
    })  

    sql, _, _ := insertDataset.ToSQL()
    assert.Equal(t, `INSERT INTO "foo" ("value1", "value2") VALUES ($1, $2)`, sql)
}
```

The test fails with the following output:

```
    user_test.go:81: 
        	Error Trace:	user_test.go:81
        	Error:      	Not equal: 
        	            	expected: "INSERT INTO \"foo\" (\"value1\", \"value2\") VALUES ($1, $2)"
        	            	actual  : "INSERT INTO \"foo\" (\"value1\", \"value2\") VALUES (?, ?)"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-INSERT INTO "foo" ("value1", "value2") VALUES ($1, $2)
        	            	+INSERT INTO "foo" ("value1", "value2") VALUES (?, ?)
        	Test:       	TestInsertDialect
```

**Comment by doug-martin** [comment]
This is most likely related to #126 i don't think I'll have time until Friday or Saturday to look at this.

**Comment by marshallmcmullen** [comment]
Thanks for the super fast response @doug-martin ! That PR does look very related. I tried to trace through the code to figure out if I was doing something wrong but I didn't get far enough to sort it all out. I'll work around this locally for now until you have time to get this resolved.

Thanks again for the awesome work and super responsiveness.

**Comment by doug-martin** [comment]
I just published v8.3.1 which includes #126 

Thanks for the bug report and let me know if you are still having issues!

**Comment by marshallmcmullen** [comment]
@doug-martin woohoo! Thank you so much for getting this merged. I will pick up the latest version and try it out tonight and update this bug with my results. Can't wait!

**Comment by marshallmcmullen** [comment]
@doug-martin I upgraded to v8.3.1 and the problem is fixed! Thank you so much for your super quick turnaround on this bug as it was driving me crazy. Awesome job.
