### ISSUE TITLE
Bug with arrays

### ISSUE THREAD

**Issue by KlimSidorov** [doug-martin/goqu#137]
Hi! Thank you for goqu library, it is very helpful.
But I have found a big problem working with arrays.

I have a struct which contains array:
```
type Hero struct {
	Id int64 `db:"id" json:"id" goqu:"skipinsert"`
	Skills []string `db:"skills" json:"skills"`
}
```
I have a function which creates a Hero (INSERT with transaction):
```
func (r Repo) InsertOneTransaction(tx *goqu.TxDatabase, h *Hero) error {
	dialect := goqu.Dialect("postgres")

	q, _, _ := dialect. // Look result query below
		Insert("heroes").
		Rows(h).
		Returning(h).
		ToSQL()

	if _, err := tx.ScanStruct(h, q); err != nil {
		return err
	}

	return nil
}
```
Result query is: 
`INSERT INTO "heroes" ("skills") VALUES (()) RETURNING "id", "skills"`

I have tested arrays with other types (like int64, float64, etc...) and goqu always transform arrays to '()' 

Looks like it is not possible to use arrays in goqu. 
If am wrong, please correct me.

**Comment by KlimSidorov** [comment]
I want to clarify the situation:

**Example 1 (empty array):**
`hero := Hero{Skills: []string{}}`
Goqu transforms it to `INSERT INTO "heroes" ("skills") VALUES (()) RETURNING "id", "skills"`

**Example 2 (array is not empty):**
`hero := Hero{Skills: []string{"flying"}}`
Goqu transforms it to `INSERT INTO "heroes" ("skills") VALUES (('flying')) RETURNING "id", "skills"`

**Comment by doug-martin** [comment]
Hi @KlimSidorov, by default goqu will serialize slices with parens because the most common use case for using them is in an `IN` clause. 

If you want the postgres array syntax II would recommend using the drivers array datatypes (https://godoc.org/github.com/lib/pq#Array).

**Comment by doug-martin** [comment]
In your example above I would use https://godoc.org/github.com/lib/pq#StringArray

**Comment by KlimSidorov** [comment]
Thank you for your response. 

In my case I have a big struct, so when I do queries I provide whole struct as an argument for `Rows()` and `Returning()`.

It is a problem for me to use pg.Array only for special fields as I have said earlier I provide whole struct (but not several fields of the struct). And if I set pg.Array as a field type, then it will be very uncomfortable to use it next in my project.

Also I use `pgx` instead of `pq` and working with types there is not so great.

I think I will use hand made sql queries for structs which contain arrays + goqu for others

**Comment by rgalanakis** [comment]
@KlimSidorov I set up this workaround, since I had the same problem.

https://gist.github.com/rgalanakis/a2d5b8b61ee9540981bb43a103bf59c7

```go
// PGArrayExpr takes a slice of items and returns a literal expression
// with a Postgres array that can be used by goqu.
// It does this by using goqu natively and then manipulating the string
// to surround it in an array literal.
//
// To use this in a struct, you can do something like:
//
//     type MyModel struct {
//       Tags   []string        `json:"tags" db:"-"`
//       DbTags goqu.Expression `json:"-" db:"tags"`
//     }
//     body := `{"tags":["x", "y"]}`
//     m := MyModel{}
//     _ = json.Unmarshal([]byte(body), &m)
//     m.DbTags = goqux.PGArrayExpr(m.Tags)
//     sql, _, _ := goqu.Insert("modeltable").Rows(m).ToSQL()
func PGArrayExpr[T any](arr []T) goqu.Expression {
  if len(arr) == 0 {
    return goqu.L("'{}'")
  }
  lit := goqu.V(arr)
  selectSql, _, err := goqu.From(lit).ToSQL()
  if err != nil {
    panic(err)
  }
  valuesSql := strings.TrimPrefix(selectSql, "SELECT * FROM ")
  if valuesSql == selectSql {
    panic("expected go to output an (invalid) 'SELECT * FROM (x, y, z)' for the slice")
  }
  if valuesSql[0] != '(' || valuesSql[len(valuesSql)-1] != ')' {
    panic("expected goqu to output '(x, y, z)' but is missing parens")
  }
  arraySql := fmt.Sprintf("ARRAY[%s]", valuesSql[1:len(valuesSql)-1])
  return goqu.L(arraySql)
}
```
