### ISSUE TITLE
ExampleDoUpdate does't work in postgres

### ISSUE THREAD

**Issue by asv** [doug-martin/goqu#156]
**Describe the bug**

https://github.com/doug-martin/goqu/blob/ce5475c8475b8cd4cdc94e201fe9c7127b9fda4b/expressions_example_test.go#L521

In the generated SQL, the EXCLUDED keyword is escaped according to goqu.I rules, however the resulting SQL is not valid for postgres.

```
INSERT INTO "items" ("address") VALUES ('111 Address') ON CONFLICT (address) DO UPDATE SET "address"="EXCLUDED"."address";
ERROR:  missing FROM-clause entry for table "EXCLUDED"
LINE 1: ...s') ON CONFLICT (address) DO UPDATE SET "address"="EXCLUDED"...
```

**To Reproduce**

Try to execute the generated code in Postgres.

**Expected behavior**

Statement must be successfully executed.

**Dialect:**

- [x] postgres

**Comment by doug-martin** [comment]
@asv good catch I took the example from https://www.postgresql.org/docs/9.5/sql-insert.html.

From the postgres docs.
```
Insert or update new distributors as appropriate. Assumes a unique index has been defined that constrains values appearing in the did column. Note that the special excluded table is used to reference values originally proposed for insertion:

INSERT INTO distributors (did, dname)
    VALUES (5, 'Gizmo Transglobal'), (6, 'Associated Computing, Inc')
    ON CONFLICT (did) DO UPDATE SET dname = EXCLUDED.dname;

```

But it appears that wont actually work.
