### ISSUE TITLE
Trouble with Database and Where Clause 

### ISSUE THREAD

**Issue by mattc41190** [doug-martin/goqu#159]
**Describe the bug**
When adding a where clause to a Database From command I get the following error:

```
"github.com/doug-martin/goqu".Ex does not implement exp.Expression (wrong type for Clone method)
have Clone() "github.com/doug-martin/goqu".Expression
want Clone() exp.Expression
```

**To Reproduce**
```go
val, _, err := r.GoquDB.From("users").Where(goqu.ExOr{"name": "doug"}).ToSQL()
```

In the above the GoquDB is of type: `*goqu.Database`

**Expected behavior**
I expected to be able to use Where as documented elsewhere. 

Kinda like: https://godoc.org/github.com/doug-martin/goqu#Database.From

**Dialect:**

- [ ] postgres 
- [ x] mysql
- [ ] sqlite3 

**Additional context**
Super interesting library! Thanks for making it!

**Comment by doug-martin** [comment]
I tried this locally and it worked as expected. Can you provide a complete example that demonstrates the issue? 

```go
db := getDb()

sql, _, _ := db.From("users").Where(goqu.ExOr{"name": "doug"}).ToSQL()
fmt.Println(sql)
```

Output
```sql
SELECT * FROM "users" WHERE ("name" = 'doug')
```

First impressions are that it looks like an import issue. 
* Are you importing the same version of goqu everywhere that you are using it? 
* How are you installing the library, for example are you go modules?

**Comment by mattc41190** [comment]
Thanks for quick response! I am presently creating a little demo to (more than likely) expose my poor documentation reading abilities :)

**Comment by mattc41190** [comment]
Confirmed -- I am bad at reading docs:

```
If using go modules.
go get -u github.com/doug-martin/goqu/v9
```

Following gist accomplishes what I originally reported. I used the import goqu from the go ref doc before seeing the v9 modules caveat.

https://gist.github.com/mattc41190/bfca7827ebbc898edaf08220d5eb3855
