### ISSUE TITLE
Mysql dialect TimeFormat strips location data

### ISSUE THREAD

**Issue by akarl** [doug-martin/goqu#163]
**Describe the bug**
When connecting to mysql the default value of `cfg.Loc` is `UTC` which means reading datetime data from mysql results in a `time.Time` with `Location` set to `UTC` even if the inserted value was in another timezone.

This happens because the `TimeFormat` of the mysql dialect strips the timezone. This became an issue after the removal of the utc conversion in `literalTime` here: https://github.com/doug-martin/goqu/pull/106

Can the dialect handle this itself somehow?
Perhaps defining `TimeFormat func(t time.Time) string` so it can be set per dialect?

**To Reproduce**
Insert a `time.Time` value with another timezone. The use `ScanStruct` to scan it in again.

**Expected behavior**
The scanned value should have the same point in time as the inserted value.

**Dialect:**

- [ ] postgres 
- [x] mysql
- [ ] sqlite3 

**Additional context**

**Comment by doug-martin** [comment]
Thank you for the bug report! Im looking into this now.

**Comment by akarl** [comment]
I’ll be happy to create a PR with my proposed solution. Or do you have another idea?

**Comment by doug-martin** [comment]
Yeah I started looking into this last night, and it appears to affect more than mysql. The approach I started taking last night was to add a `ConvertTimeToUTC` config to allow forcing of UTC conversion (You can take a look at https://github.com/doug-martin/goqu/commit/92f4fd59f837754c28f74d722d97879e8d97c307) I think this should be the default behavior. 

Let me know what you think.

**Comment by doug-martin** [comment]
@akarl I didnt really address your question in my comment, sorry. 

If you also want to try your solution go for it, it might just be an option you can set on the DialectOptions if `TimeFormat` isn't enough.

**Comment by doug-martin** [comment]
Ok I think I came up with an acceptable solution that should work for all dialects. Let me know what you think. https://github.com/doug-martin/goqu/pull/167/commits/a9254f57f0d3d957a1f5b5174e5436daa80a09bd

I changed the default back to `UTC` for all `time.Time` instances, however there is a new method `SetTimeLocation` which allows you to specify an alternate timezone, incase UTC doesnt work.

**Comment by akarl** [comment]
I like it! I left a review on the PR. And I think this solution is much better than the one I had in mind!

**Comment by doug-martin** [comment]
Released!
