### ISSUE TITLE
with table as (insert ... returning ...)

### ISSUE THREAD

**Issue by cmoad** [doug-martin/goqu#164]
**Is your feature request related to a problem? Please describe.**
We are trying to convert a query that has a common table expression that is a result of `insert...returning`. We are getting the error `goqu: unsupported expression type *goqu.InsertDataset` from the sql generator.

**Describe the solution you'd like**
Adding a case for InsertExpression to https://github.com/doug-martin/goqu/blob/25020dc497ec58c3dbfe98190ac30ff72b0f59d2/sqlgen/expression_sql_generator.go#L140

**Describe alternatives you've considered**
N/A

**Dialect**
- [x] postgres
- [ ] mysql
- [ ] sqlite3

**Additional context**
Opening this issue. We think we know the fix, but need to fork and setup our dev environments to get you a PR. Thanks for all the awesome work lately! We would like to contribute where possible.

**Comment by cmoad** [comment]
I may have spoken too soon. I attempted to add support for InsertExpression in expression_sql_generator.go, but it's causing an infinite loop in the test case.

Here was the naive attempt:
```golang
// Generates SQL for an InsertExpression
func (esg *expressionSQLGenerator) insertExpressionSQL(b sb.SQLBuilder, ie exp.InsertExpression) {
	esg.Generate(b, ie)
}
```

**Comment by doug-martin** [comment]
I think I know the fix for this. Ill start diving in today

**Comment by doug-martin** [comment]
I just issued a PR that addresses this issue. In `v9.3.0` you will be able to use `Insert`, `Update` or `Delete` datasets in CTEs and sub queries as long as they have a `RETURNING` clause.

**Comment by cmoad** [comment]
Awesome. Thanks for tackling that. Looks like it was more involved than we were expecting.

**Comment by doug-martin** [comment]
Yeah it could have been less invasive but I decided to go ahead and support all the datasets instead of just insert. I’m going to get the coverage passing and then publish. 

Thanks for submitting the feature request!

**Comment by doug-martin** [comment]
published!
