### ISSUE TITLE
time.Time column output json format

### ISSUE THREAD

**Issue by baiy** [doug-martin/goqu#170]
```go
//  struct
type Model struct {
	Id         int       `json:"id" goqu:"skipinsert,skipupdate"`
	CreateTime time.Time `json:"create_time" goqu:"skipinsert,skipupdate"`
	UpdateTime time.Time `json:"update_time" goqu:"skipinsert,skipupdate"`
}


```
`json.Marshal()`  after 
output `create_time`:2019-09-20T16:26:13+08:00
expect  `create_time`:2019-09-20 16:26:13

Cannot be solved using the following methods
<https://stackoverflow.com/questions/23695479/format-timestamp-in-outgoing-json-in-golang>

**Dialect**
- [ ] postgres
- [x] mysql
- [ ] sqlite3

**Comment by doug-martin** [comment]
@baiy Im not sure I understand? `goqu` doesn't have anything to do with JSON marshalling.

If you can provide some more context I can try to help.

**Comment by baiy** [comment]
@doug-martin  The issues wasn't caused by `goqu `
close issues
thanks
