### ISSUE TITLE
Unsupported expression type regexpilike

### ISSUE THREAD

**Issue by marshallmcmullen** [doug-martin/goqu#172]
**Describe the bug**

I'm not sure if this is intentionally not supported or if it's an oversight, but I tried to use `RegexpILikeOp` inside `Ex` and it failed with:

```
goqu: unsupported expression type map[regexpilike:.*.gmail.com]"
```

**To Reproduce**
If applicable provide a small code snippet to reproduce the issue:

```
sql, args, err := goqu.From("items").Where(
    goqu.Ex{
        "col1": goqu.Op{"regexpilike": ".*.gmail.com"},
    },
)
assert.Nil(err)
// Error: Expected nil, but got: errors.Error{err:"goqu: unsupported expression type map[regexpilike:.*.gmail.com]"}
```

**Expected behavior**

All the SQL operations goqu supports should be valid inside Ex Map. 

**Dialect:**

- [X] postgres 
- [ ] mysql
- [ ] sqlite3 

**Additional context**

**Comment by doug-martin** [comment]
Currently this is handled internally when a regex is encountered. 

I don't see a reason why you shouldn't be able to specify that you want to use the regex like comparison. Ill go ahead and add this.

**Comment by doug-martin** [comment]
Released as `v9.5.0`

**Comment by marshallmcmullen** [comment]
Holy smokes you are fast! Thanks for adding this, I appreciate it very much!!!

**Comment by marshallmcmullen** [comment]
Thanks again for doing this so quickly @doug-martin . I reviewed the changes and was impressed by all the added testing too. Awesome stuff.
