### ISSUE TITLE
Add Lateral Query

### ISSUE THREAD

**Issue by arddor** [doug-martin/goqu#182]
**Is your feature request related to a problem? Please describe.**
Currently I found no way to use a [lateral subquery](https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-LATERAL). 

**Describe the solution you'd like**
Ideally a `Lateral` or `LateralJoin` would be added to the syntax.

**Dialect**
- [x] postgres
- [ ] mysql
- [ ] sqlite3

**Comment by doug-martin** [comment]
@arddor please checkout #191 let me know what you think.

**Comment by arddor** [comment]
Looks good, thank you

**Comment by doug-martin** [comment]
Released!
