### ISSUE TITLE
Add support of CASE conditional expression

### ISSUE THREAD

**Issue by o1egl** [doug-martin/goqu#193]
Add support of `CASE` expression
```
CASE
    WHEN expression THEN value
    WHEN expression THEN value
END
```

postgres: https://www.postgresql.org/docs/9.4/functions-conditional.html
mysql: https://dev.mysql.com/doc/refman/5.7/en/case.html
sqlite3: https://www.sqlitetutorial.net/sqlite-case/

**Dialect**
- [x] postgres
- [x] mysql
- [x] sqlite3

**Comment by doug-martin** [comment]
Released in `v9.8.0`
