### ISSUE TITLE
Support MS SQL Server

### ISSUE THREAD

**Issue by vasayxtx** [doug-martin/goqu#197]
Hi,
Thanks for the great query builder! What do you think about supporting Microsoft SQL Server?

**Comment by doug-martin** [comment]
Yeah, I would have no problems with that if you want to create a PR with the adapter and tests that would be great!

**Comment by vlanse** [comment]
@doug-martin looks like this could be closed now.
btw, do you plan to merge sqlserver support in master branch also?

**Comment by doug-martin** [comment]
@vlanse yeah I will once, I do all the house keeping stuff with the release

**Comment by doug-martin** [comment]
Released in v9.7.0
