### ISSUE TITLE
Custom Expressions - example

### ISSUE THREAD

**Issue by talpa** [doug-martin/goqu#199]
Hi Martin,
I need custom expression or any solution for this  "Where" example

WHERE(`date_trunc('DAY', ac.created_at + INTERVAL '1  DAY' * ac.net) < current_timestamp - INTERVAL '1 DAYS' * ? ,dayInterval))`

Thanks

Ales
**Dialect**
- [x] postgres
- [x] mysql
- [x] sqlite3

**Additional context**

**Comment by doug-martin** [comment]
Hi @talpa checkout [`goqu.Func`](https://godoc.org/github.com/doug-martin/goqu#Func) it allows you to create reusable functions like this.

Here is a quick example of breaking down the parts of your `WHERE` clause into reusable functions

```go
dateTrunc := func(text string, timestamp exp.Expression) exp.SQLFunctionExpression {
	return goqu.Func("date_trunc", text, timestamp)
}
interval := func(interval string) goqu.Expression {
	return goqu.L("INTERVAL ?", interval)
}
dayInterval := interval("3 days")
ac := goqu.T("ac")
sql, _, _ = goqu.From(ac).Where(
	dateTrunc("DAY", goqu.L("? + ? * ?", ac.Col("created_at"), interval("1 DAY"), ac.Col("net"))).
		Lt(goqu.L("current_timestamp - ? * ?", interval("1 DAYS"), dayInterval)),
).ToSQL()
fmt.Println(sql)
```

Output:
```
SELECT * FROM "ac" WHERE (date_trunc('DAY', "ac"."created_at" + INTERVAL '1 DAY' * "ac"."net") < current_timestamp - INTERVAL '1 DAYS' * INTERVAL '3 days')
```

**Comment by talpa** [comment]
thanks Great :)
