### ISSUE TITLE
[Question] IN queries

### ISSUE THREAD

**Issue by ldelossa** [doug-martin/goqu#200]
**Describe the bug**
This is a Question 

Does goqu support "IN" queries.

**Comment by doug-martin** [comment]
Yep! Checkout the [expressions docs](https://github.com/doug-martin/goqu/blob/master/docs/expressions.md) there are a couple of examples of `IN` and `NOT IN` expressions.

```go
sql, _, _ := db.From("items").Where(goqu.Ex{
  "col": []string{"a", "b", "c"},
}).ToSQL()
fmt.Println(sql)
```

Output

```
SELECT * FROM "items" WHERE ("col" IN ('a', 'b', 'c'))
```
