### ISSUE TITLE
[Question] Is there a way to do custom operation

### ISSUE THREAD

**Issue by blackpawninja** [doug-martin/goqu#202]
i am using **LTree** extension on **postgresql**, it adds some [operators](https://www.postgresql.org/docs/current/ltree.html#id-1.11.7.30.5) to column type `ltree`

reading goqu docs, it seems the available operators are hardcoded, so i can't use unknown operator like `@>` 

**is there a way to do custom operator expression?**

**Dialect**
- [x] postgres
- [ ] mysql
- [ ] sqlite3

**additional notes**
postgres also have [JSON operators](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-PROCESSING)

**Comment by doug-martin** [comment]
@blackpawninja Sorry for the delay in responding.

There currently isnt a way to add custom operators, however you can use `goqu.L` to achieve something similar.

For example I have used the following for json operators.

```go
jsonTextLookup := func(col exp.Expression, field string) goqu.Expression {
	return goqu.L("?->>?", col, field)
}

sql, _, _ = goqu.From("foo").Select(
	jsonTextLookup(goqu.C("jsonField"), "jsonProperty"),
).ToSQL()
fmt.Println(sql)
```
Output:
```
SELECT "jsonField"->>'jsonProperty' FROM "foo"
```
