### ISSUE TITLE
About configuration  sql_mode=ANSI_QUOTES in MySQL

### ISSUE THREAD

**Issue by kkdai** [doug-martin/goqu#21]
Hi, 
Thanks for your great package, I am wondering why the SQL always get quote in table name?
`
   db.From("user").ToSql()  // SELECT * from "user"
`

It might be issue if user don't set environment parameter in MySQL 

`
mysql> SET sql_mode='ANSI_QUOTES';
`

or in their connect string 

`
db_uri = fmt.Sprintf("%s:%s@tcp(%s)/%s?timeout=30s&parseTime=true&sql_mode='ANSI_QUOTES'", user, pass, addr, dbname)
`
Otherwise it will always get error at beginning.

Do you think it would be more clear to add this setting in test case or document?

**Comment by cdujeu** [comment]
See #44 - you probably did not register the mysql adapter correctly

**Comment by doug-martin** [comment]
Closed but Ill address this in https://github.com/doug-martin/goqu/issues/44#issuecomment-509823342
