### ISSUE TITLE
Error 1064: You have an error in your SQL syntax

### ISSUE THREAD

**Issue by enverbisevac** [doug-martin/goqu#219]
**Describe the bug**
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"account_myuser" WHERE ("id" = 2) LIMIT 1' at line 1

**To Reproduce**
`db := goqu.New("mysql", repository.conn)
ds := db.From("account_myuser").Where(goqu.C("id").Eq(id))`

**Expected behavior**
toSQL return string: SELECT * FROM "account_myuser" WHERE ("id" = 2)
I am using MySQL version: 5.5.5-10.4.10-MariaDB-1:10.4.10+maria~bionic

**Dialect:**

- [ ] postgres 
- [X] mysql
- [ ] sqlite3 

**Additional context**

**Comment by ramonberrutti** [comment]
You import the mysql dialect?

````
import         _ "github.com/doug-martin/goqu/v9/dialect/mysql"
```

and use
```
	dialect := goqu.Dialect("mysql")
```

**Comment by enverbisevac** [comment]
Yes, I did and it worked, but I forgot to close the ticket :)
