### ISSUE TITLE
I can not import the package correctly!!

### ISSUE THREAD

**Issue by kooksee** [doug-martin/goqu#22]
```go
* gopkg.in/doug-martin/goqu.v3
* gopkg.in/doug-martin/goqu.v3/adapters/postgres


* github.com/doug-martin/goqu
* github.com/doug-martin/goqu/adapters/postgres
```
which is correctly??
yeah, I can `go get github.com/doug-martin/goqu` and `github.com/doug-martin/goqu/adapters/postgres  `,but I find `gopkg.in/doug-martin/goqu.v3` in the postgres package ,so I am very confused !!

**Comment by doug-martin** [comment]
Just import `gopkg.in/doug-martin/goqu.v3` and `gopkg.in/doug-martin/goqu.v3/adapters/postgres`

**Comment by doug-martin** [comment]
Also install the gopkg.in version

```
go get -u gopkg.in/doug-martin/goqu.v3
```
