### ISSUE TITLE
How To Do A UPSERT Query

### ISSUE THREAD

**Issue by ashu8912** [doug-martin/goqu#224]
An Upsert query looks something like How do we prepare such a query with current Insert syntax
INSERT INTO table_name(column_list) VALUES(value_list) ON CONFLICT target action;

**Comment by doug-martin** [comment]
@ashu8912 take a look at https://godoc.org/github.com/doug-martin/goqu#InsertDataset.OnConflict

**Comment by ashu8912** [comment]
Thanks @doug-martin

**Comment by wirekang** [comment]
@doug-martin link is broken.
