### ISSUE TITLE
MySql supports numeric field values ​​ +1

### ISSUE THREAD

**Issue by mooczhou** [doug-martin/goqu#226]
MySql supports numeric field values ​​from +1, but I found that after exp.Record conversion will be treated as a string
follows
g.Record{"rec": "`rec` + 1"}
conversion
`rec` =  '`rec` + 1'
However I just want to get something like this
`rec` =  `rec` + 1
Do you have a better solution for this?

**Comment by phperfan** [comment]
```
goqu.Record{
	"index": goqu.L("index +1"),
}
```
