### ISSUE TITLE
Literal tables name aliases for joins On Hive Query

### ISSUE THREAD

**Issue by nagaame** [doug-martin/goqu#245]
Hi, I use this library to build my hive sql, but hive sql grammar not allowed join options table name aliases is strings, only allowed Literal name 

library function As() only support strings

example:

❎ bad: 
`select * from (select * from users where id == 1) as "t1" inner join (select * from profile where id == 1) as "t2" on t1.name == t2.name`

✅good:
`select * from (select * from users where id == 1) as t1 inner join (select * from profile where id == 1) as t2 on t1.name == t2.name`

✅good:
```select * from (select * from users where id == 1) as `t1` inner join (select * from profile where id == 1) as`t2` on t1.name == t2.name```

How should I do, thanks🙏

**Comment by crashiura** [comment]
Hi, show please code ?
