### ISSUE TITLE
Opt-in struct field persistence

### ISSUE THREAD

**Issue by Deiz** [doug-martin/goqu#284]
:wave: I have a few wants I'll likely be implementing in the coming days and would be curious as to whether you'd accept them upstream. Generally, these are centred around using goqu in an opt-in, rather than opt-out manner: I only want goqu to concern itself with explicitly-tagged fields.

Currently, only the `db:"-"` struct tag can be used to avoid including a field in the select column set. There are no magic values like `"-"` from the `columnRenameFunction` that can be used to control this, either.

I'm planning to add one (or both?) of these: 
1. Likely a global `goqu.IgnoreUntaggedFields()` or similar that skips fields during `Select()` etc. that don't have a tag set
2. Some flavour of `goqu.SetExtendedColumnRenameFunction(func(field *reflect.StructField) (colname string, ok bool))` where, if `ok == false`, the field is ignored during `Select()` and others - with the side benefit of exposing the raw `*reflect.StructField` to the rename function.

**Comment by doug-martin** [comment]
@Deiz that makes sense to me, glad to have new contributors!

**Comment by Deiz** [comment]
Going to close this out, cheers for the quick review.
