### ISSUE TITLE
Select static values 

### ISSUE THREAD

**Issue by k1ng440** [doug-martin/goqu#329]
**Is your feature request related to a problem? Please describe.**
Hello,
I like to be able to make queries like this with postgres dialect 

```
select symbol, start_time, end_time from (values ('btc-bitcoin', now() - INTERVAL '24 hours', now()), ('btc-bitcoin', now()-interval '24 hours', now())) s(symbol, start_time, end_time)
```

**Describe the solution you'd like**

A goqu way to make queries like this

**Describe alternatives you've considered**

I have no idea how to do this with goqu.

**Dialect**
- [ x ] postgres
- [ ] mysql
- [ ] sqlite3

**Additional context**

**Comment by hakanutku** [comment]
@k1ng440 How did you managed to build VALUES lists in goqu? Can you share your solution?

**Comment by k1ng440** [comment]
@hakanutku you have to wrap it in `goqu.L()`

```
From(goqu.L(fmt.Sprintf("(values %s) AS s(symbol, start_time, end_time)", strings.Join(values, ", "))))
```
