### ISSUE TITLE
Prepared(true) issues when using IS NULL comparisson operation

### ISSUE THREAD

**Issue by danielfbm** [doug-martin/goqu#33]
Hi, 
First of all, thank you very much for this amazing library. I have been using it for a week or so, and I found it to be very useful and very quick to get used to.

I am still facing a weird issue when doing selects using `goqu.I("column").IsNull()`. If the query is `Prepared(true)`  then this would generate a following condition: `"column" IS $1` and that is not allowed in different databases. I didnt get it to work with psql.

I think this, although is prepared, could keep the IS NULL as this is not really a parameter.

**Comment by doug-martin** [comment]
I agree it seems we handle that for `TRUE` and `FALSE` but not `NULL` if you want to open a PR that would be great not sure when Ill have time to get to this.

I would start here https://github.com/doug-martin/goqu/blob/master/default_adapter.go#L815 and add some tests to the select tests both prepared and not https://github.com/doug-martin/goqu/blob/master/dataset_select_test.go.

**Comment by danielfbm** [comment]
@doug-martin I opened a pull-request for this. I updated the relevant tests and ran all of them with the compose file (+1 for that) 
Take your time to review and let me know If there is something wrong in there...
