### ISSUE TITLE
How to write where expression if i want to query json property when use postgres?

### ISSUE THREAD

**Issue by rayunstop** [doug-martin/goqu#332]
I saw the method to query json property like:
```go
	jsonTextLookup := func(col exp.Expression, field string) goqu.Expression {
		return goqu.L("?->>?", col, field)
	}

	sql, _, _ = goqu.From("foo").Select(
		jsonTextLookup(goqu.C("jsonField"), "jsonProperty"),
	).ToSQL()
	fmt.Println(sql)
```

But how to put it to where case?
The Expression Ex is a map, and the key is string, not expression interface.
The question is how to impl:
```sql
where "jsonField" ->> 'jsonProperty' = XXX.
```

**Comment by akarl** [comment]
I'm not sure about postgres but in mysql you can do something like `goqu.Func("JSON_EXTRACT", col, '$.property')`.

Seems like postgres has a `json_extract_path` function that you can use?

**Comment by francistm** [comment]
the signature of where is `func (sd *SelectDataset) Where(expressions ...exp.Expression) *SelectDataset`, which expression is not a map.

``` golang
sql, _, _ := goqu.From("tbl").Where(goqu.L("?->>?", goqu.C("foo"), "bar").Eq("baz")).ToSQL()
log.Printf("sql: %s", sql) 
// output sql: SELECT * FROM "tbl" WHERE ("foo"->>'bar' = 'baz')
```

**Comment by rayunstop** [comment]
> the signature of where is `func (sd *SelectDataset) Where(expressions ...exp.Expression) *SelectDataset`, which expressions are not map nor []map.
> 
> ```go
> sql, _, _ := goqu.From("tbl").Where(goqu.L("?->>?", goqu.C("foo"), "bar").Eq("baz")).ToSQL()
> log.Printf("sql: %s", sql) 
> // output sql: SELECT * FROM "tbl" WHERE ("foo"->>'bar' = 'baz')
> ```

nice, thanks!

**Comment by rayunstop** [comment]
problem solved.
