### ISSUE TITLE
go 1.19.2 mysql dialect dont load

### ISSUE THREAD

**Issue by kirill-lokhmatov** [doug-martin/goqu#371]
hello a am doing imports not in main.go
> package mysql
> import (
> 	"github.com/doug-martin/goqu/v9"
> 	_ "github.com/doug-martin/goqu/v9/dialect/mysql"

mysql dialect is not selected, it still escapes double-quoted table and field names.

Tried to register manually
>goqu.RegisterDialect("mysql", md.DialectOptions())
>goqu.RegisterDialect("mysql8", md.DialectOptionsV8())

Still dont work
Only this helps but i dont want to set dialect each time
> query, _, _ := goqu.Dialect("mysql8").From

v9.18.0

**Comment by kirill-lokhmatov** [comment]
finally got it

**Comment by kirill-lokhmatov** [comment]
finally got it

**Comment by erwanlbp** [comment]
Hello,
I encountered the same problem, can you explain your "finally got it" please :)

**Comment by kirill-lokhmatov** [comment]
you should create goqu database object first

> goqu.New(dialect, db).From()...
