### ISSUE TITLE
mysql dialect DELETE syntax error

### ISSUE THREAD

**Issue by Fanduzi** [doug-martin/goqu#378]
**Describe the bug**
mysql dialect DELETE statement generates error

**To Reproduce**
```go
package main

import (
	"fmt"

	"github.com/doug-martin/goqu/v9"
	_ "github.com/doug-martin/goqu/v9/dialect/mysql"
)

func main() {
	dialect := goqu.Dialect("mysql")

	sql, _, _ := dialect.Delete("table").ToSQL()
	fmt.Println(sql)
}
```

```
go run bug/main.go
DELETE `table` FROM `table`
```
![image](https://user-images.githubusercontent.com/24428128/220046664-52183abd-7f2b-4066-a6d0-70e9ceeb9ef6.png)

**Expected behavior**
expect
```
DELETE FROM `table`
```

**Dialect:**

- [ ] postgres (not test)
- [x] mysql
- [ ] sqlite3  (ok)

**Additional context**

**Comment by user3690** [comment]
@Fanduzi Thats not really a bug. Yes, `DELETE FROM `abc` WHERE `id` = 1;` is the shortest form, but the result of the query builder is not wrong. It is the multiple table syntax. See [link](https://dev.mysql.com/doc/refman/8.0/en/delete.html).

**Comment by Fanduzi** [comment]
> @Fanduzi Thats not really a bug. Yes, `DELETE FROM abc WHERE id = 1;` is the shortest form, but the result of the query builder is not wrong. It is the multiple table syntax. See [link](https://dev.mysql.com/doc/refman/8.0/en/delete.html).

you are right, thank you!
