### ISSUE TITLE
Do not interpolate parameters by default

### ISSUE THREAD

**Issue by pprishchepa** [doug-martin/goqu#396]
**Is your feature request related to a problem? Please describe.**
I suddenly noticed that goqu interpolates the parameters by default. As I understand, it's not as good and makes the injections possible. What was the motivation for it?

**Describe alternatives you've considered**
Is there a way to not use interpolation by default?

**Comment by funkyshu** [comment]
See https://pkg.go.dev/github.com/doug-martin/goqu#Dataset.Prepared

**Comment by veqryn** [comment]
@funkyshu why is interpolation the default?
Why did goqu go to all the trouble to write an interpolation layer, when every database takes parameters?
