### ISSUE TITLE
Upgrading from v3 to v4

### ISSUE THREAD

**Issue by danielfbm** [doug-martin/goqu#40]
Not a library issue, just a suggestion to add possible changes from v3 to v4. Didn't really found anything on the README, is it 100% compatible? 

If there are any changes, maybe a wiki entry would be helpful

Thanks in advance

**Comment by doug-martin** [comment]
Hi, there are a couple of places that we keep the change log

*  https://github.com/doug-martin/goqu/releases/tag/v4.0.0
* https://github.com/doug-martin/goqu/blob/master/HISTORY.md

Hope this helps!
