### ISSUE TITLE
Possible Issue with Saving/Reading Byte Array

### ISSUE THREAD

**Issue by yubing24** [doug-martin/goqu#41]
Before I switched to goqu, I was using following sql to store password salt and hash to PostgreSQL:
`INSERT INTO ACCOUNT (SALT, HASH) VALUES ($1, $2);`
and I passed `[]byte` values to both arguments. The corresponding columns in my database are type `bytea`. I was using `sha256` from go's crypto package to generate the hash. When I read the salt and hash, I also read them to `[]byte` objects and the authentication worked fine.
However, this is not working when I was using goru with following code:
`sql,_, _:=db.From("ACCOUNT").Select(goqu.I("SALT"),goru.I("HASH")).Where(goqu.Ex{"USERNAME": username}).ToSql()`
`rows, err := db.Query(sql)`
Password no longer matches the hash with the given salt.
I checked my schemas, columns, and values and confirmed that all these values are correct. 
I also looked into your tests but did not find any examples for saving or reading `[]byte` or `bytea` type. Most of them are for numeric or string(array) types.
Does goqu support `[]byte` or did I miss something? Thanks!

**Comment by doug-martin** [comment]
Looking at the example you provided the `db.Query` method doesn't do anything special it will just use the underlying Query method from the driver. Can you provide a failing example?
