### ISSUE TITLE
sqlite3 dialect incorrectly states RETURNING clause isn't supported

### ISSUE THREAD

**Issue by yktoo** [doug-martin/goqu#432]
The implementation of the `sqlite3` dialect (`dialect/sqlite3/sqlite3.go`) configures `opts.SupportsReturn = false`. However, the SQLite driver does support `RETURNING` (see [docs](https://www.sqlite.org/lang_returning.html)), which can easily be verified by dropping to the default dialect while using an SQLite3 database.

**Dialect:**

- [ ] postgres 
- [ ] mysql
- [x] sqlite3

**Comment by Func86** [comment]
Addressed in https://github.com/doug-martin/goqu/commit/7ff091d4521d0ee17a0b4abc01a200091cfc208f but not released.

**Comment by yktoo** [comment]
Thanks @Func86. Closing as a duplicate of #358.
