### ISSUE TITLE
Not using mysql adapter

### ISSUE THREAD

**Issue by kumarsiva07** [doug-martin/goqu#44]
`package main

import (
	"fmt"
	"time"

	"database/sql"

	"github.com/doug-martin/goqu"
	_ "gopkg.in/doug-martin/goqu.v4/adapters/mysql"
	_ "github.com/go-sql-driver/mysql"
)

func main() {

	var mtObject User
	orgId := 1
	objectId := 1

	mysqlDb, err := sql.Open("mysql", "root:@/")
	if err != nil {
		panic(err.Error())
	}
	mysqlDb.SetMaxIdleConns(10)
	mysqlDb.SetMaxOpenConns(20)
	db := goqu.New("mysql", mysqlDb)
	db.Db.Exec("use test")

	found, err := db.From(goqu.I("table").As("t")).Select("*").Where(
		goqu.I("id").Eq(objectId),
		goqu.I("org_id").Eq(orgId),
	).ScanStruct(&mtObject)

	if err != nil {
		fmt.Println(err.Error())
		return
	}
	if !found {
		fmt.Println("No object found")
	} else {
		fmt.Printf("\nFound object: %+v", mtObject)
	}

}
`

**Comment by kumarsiva07** [comment]
I am getting error 
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"table" AS "t" WHERE (("id" = 1) AND ("org_id" = 1)) LIMIT 1' at line 1


> This because of double quotes. How to enable mysql adapter for `

**Comment by doug-martin** [comment]
Can you try importing changing `"github.com/doug-martin/goqu"` to `gopkg.in/doug-martin/goqu.v4`

**Comment by RoarkeRandall** [comment]
I'm also having a similar issue. I'm using postgres but the prepared statements being generated use `?` instead of `$1`. I'm importing the postgres adapter. One thing that might affect it is that I'm using the static `goqu.From` as opposed to `db.From`

**Comment by padand** [comment]
@RoarkeRandall I was having a similar problem using it like that. This is my workaround:

```
dataset := goqu.From("test")
dataset = dataset.SetAdapter(goqu.NewAdapter("mysql", dataset))
dataset.ToSql()
```

**Comment by doug-martin** [comment]
Im going to add a section about dialects in `goqu` to help clear up some of this confusion. In the initial example I think the issue comes from using two different versions of `goqu` but this deserves its own section in the readme.
