### ISSUE TITLE
Offline SQL building

### ISSUE THREAD

**Issue by MTCoster** [doug-martin/goqu#45]
As far as I can tell, there is currently no way to initialize a SQL builder without creating a database instance.  Why is this, since I'd have thought the database connection is only necessary for querying after building?

My potential use case simply involves generating SQL strings, not necessarily querying them.

**Comment by nd2s** [comment]
`goqu.From()` and then `.ToSql()`? That's how I'm using goqu...

**Comment by MTCoster** [comment]
I suspect that makes this a documentation enhancement issue, rather than a code enhancement issue.  I had no idea you could call `From()` statically like that.

**Comment by nd2s** [comment]
I think it's pretty obvious on godoc, `From()` is the constructor of `Dataset`. Although the documentation of `From()` is a bit strange.

**Comment by TechnotronicOz** [comment]
You could get the sql fairly easily. You should have `ToSql, ToUpdateSql, ToDeleteSql, ToInsertSql, ToTruncateSql` methods available on the dataset to generate the raw sql.

```go
sql, _, err := db.From("my_table").Select("other_column").Where(goqu.Ex{"my_column": true}).ToSql()
fmt.Println(sql) // select other_column from my_table where my_column is true;

sql, _, err = db.From("my_table").Where(goqu.Ex{"my_column": true}).ToUpdateSql(goqu.Record{"another_column": false})
fmt.Println(sql) // update my_table set another_column = false where my_column is true;
```

@nd2s What do you think we can do to help improve the documentation?

**Comment by nd2s** [comment]
@TechnotronicOz I found the `Typically you would use Database#From.` part a bit strange. Because as the README says in line 1 `goqu is an expressive SQL builder`. Its main purpose is to build SQL, not to execute it. The execution part is just a nice-to-have.

Also the examples in the README should probably begin with building SQL without executing it, and then showing the generated query. Currently it partly starts off like some generic ORM which is kind of underselling it. (`goqu` is the only usable package I found for dynamically building complex SQL expressions).

**Comment by TechnotronicOz** [comment]
@nd2s I see what you are saying. Goqu came about b/c we didn't like having raw sql in our codebase and Goqu sort of mirrors our Node query builder lib [Patio](https://github.com/C2FO/patio). If you'd like, feel free to open a PR with updates to the documentation.

We predominately use it to both the query building and execution, something like:

```go
type CompanyRecord struct {
    Id uint64 `db:"id" goqu:"skipinsert,skipupdate"`
    Name string `db:"name"`
}

func CreateRecord(companyId uint64, name string) (*CompanyRecord, error) {
    record := goqu.Record{
        "id": companyId,
        "name": name,
    }
    newRecord := CompanyRecord{}
    if _, err := db.From("table").Returning(goqu.I("id"), goqu.I("name")).Insert(record).ScanStruct(&newRecord); err != nil {
        return newRecord, err
    }
    return newRecord, nil
}
```

**Comment by doug-martin** [comment]
In `v7` I have added a new [`Dialect`](https://godoc.org/github.com/doug-martin/goqu#Dialect) method to address this very problem. When creating this we always used it in tandem with a Db but it seems people are using it just for sql generation. 

Here is an example creating using just the mysql dialect without a db.
```go
import _ "github.com/doug-martin/goqu/v7/dialect/mysql"

dialect := goqu.Dialect("mysql")
ds := dialect.From("test").Where(goqu.Ex{
    "foo": "bar",
    "baz": []int64{1, 2, 3},
}).Limit(10)

sql, args, _ := ds.ToSQL()
fmt.Println(sql, args)

sql, args, _ = ds.Prepared(true).ToSQL()
fmt.Println(sql, args)
```
Output:
```
SELECT * FROM `test` WHERE ((`baz` IN (1, 2, 3)) AND (`foo` = 'bar')) LIMIT 10 []
SELECT * FROM `test` WHERE ((`baz` IN (?, ?, ?)) AND (`foo` = ?)) LIMIT ? [1 2 3 bar 10]
```
