### ISSUE TITLE
Sphinx Search Adapter

### ISSUE THREAD

**Issue by robertmeta** [doug-martin/goqu#5]
Just wondering if you would be interested in a Sphinx Search Adapter -- it technically isn't a database, but it speaks the MySQL protocol but the query language is similar but different: http://sphinxsearch.com/docs/current.html#sphinxql-reference

**Comment by doug-martin** [comment]
Hi Robert,

Yeah if you would like to work on a SphinxQL adapter, that would be cool. 
Im assuming you can just use the MySQL driver to execute queries?

-Doug

**Comment by robertmeta** [comment]
Correct.  Just needs different query syntax & rules.
