### ISSUE TITLE
TxDatabase.Wrap() does not perform Rallback() in case of panic.

### ISSUE THREAD

**Issue by nikolay-turpitko** [doug-martin/goqu#53]
TxDatabase.Wrap() does not perform Rollback() in case of panic.
It's trivial to fix or workaround, but it either should be fixed or documented properly.

**Comment by TechnotronicOz** [comment]
@nikolay-turpitko once the supplied function is done, it'll complete or rollback the transaction. I would recommend handling the error and only panic-ing when absolutely necessary. I may be missing something, if so, please provide an example or test-case as best I can tell, it is working like it should.

```go
tx, err := db.Begin()
if err != nil{
     panic(err.Error()) //you could gracefully handle the error also
}
if err := tx.Wrap(func() error{
    if _, err := tx.From("test").Insert(Record{"a":1, "b": "b"}).Exec(){
        //this error will be the return error from the Wrap call
        // should rollback here
        return err
    }
    // should commit here
    return nil
}); err != nil{
     panic(err.Error()) //you could gracefully handle the error also
}
```

**Comment by nikolay-turpitko** [comment]
@TechnotronicOz I suggest to add a phrase to the function's description like "Notice, that this function does not rollback transaction in case of panic, handle it yourself" and close this issue. Looking on the documentation alone I thought that it'd rollback in case of panic for me.

**Comment by TechnotronicOz** [comment]
https://godoc.org/github.com/doug-martin/goqu#TxDatabase.Wrap

**Comment by nikolay-turpitko** [comment]
@TechnotronicOz yes, this is the place where you could add this sentence. Probably, my English is not particularly well, it's not my mother tongue after all, but from the current doc it's not immediately clear for me, that in case of panic transaction neither committed or rolled back. If you think it's clear enough, then it's just my fault. Feel free to close the issue. Thanks!
