### ISSUE TITLE
builder added quotes in fieldNames

### ISSUE THREAD

**Issue by chaevnicher** [doug-martin/goqu#58]
```
insert := Db.From("log").Insert(goqu.Record{
	"code" : "10",
	"data" : "connection ok",
})
```

return error: 

> Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"log" ("code", "data") VALUES ('10', 'connection ok')' at line 1

mysql needed _(code, data) VALUES ('10', 'connection ok');_ but not _("code", "data")_

**Comment by chaevnicher** [comment]
Db = goqu.New("mysql", mysqldb)
		insert := Db.From("log").Insert(goqu.Record{"code": 10, "data":"data1"})
		if _, err := insert.Exec(); err != nil{
			fmt.Println(err.Error())
			return
		}

Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"log" ("code", "data") VALUES (10, 'data1')' at line 1

**Comment by chaevnicher** [comment]
???

**Comment by TechnotronicOz** [comment]
@chaevnicher do you get the error if you use a struct for your insert like in https://github.com/doug-martin/goqu/blob/master/adapters/mysql/mysql_test.go#L226?

**Comment by chaevnicher** [comment]
I dont use structure like in example.

**Comment by Elbandi** [comment]
The error is: table and field names are quoted in builded query, mysql doesnt like it, query sould be something line this:

    INSERT INTO log (code, data) VALUES ('10', 'connection ok')

**Comment by cdujeu** [comment]
See #44, the mysql adapter may not be registered correctly
