### ISSUE TITLE
Add support for passing context.Context

### ISSUE THREAD

**Issue by blockloop** [doug-martin/goqu#59]
Please add support for passing context.Context to `database` funcs to allow cancellation of long running queries.

**Comment by leebenson** [comment]
what would be the use-case for this? As a SQL builder, I'm currently passing context through the usual chain... HTTP, GraphQL handlers, etc... rather than the builder itself.

I'm new to this lib, so genuinely curious where you might find a need for context, so I can understand what some of the current limitations might be.

**Comment by blockloop** [comment]
When calling [`Exec`](https://godoc.org/github.com/doug-martin/goqu#Database.Exec) without Context, the call chain will hang until the database connection is allowed to execute the query, even if the client cancels context. This can clog the database with waiting processes.

**Comment by leebenson** [comment]
wouldn't it just be a case of checking that Context hasn't been canceled before running `Exec`?

**Comment by blockloop** [comment]
That would be okay, but after you call `(sql.DB*).Exec` the process can enter several states such as waiting for a table lock (the most common). Sometimes, if the table is locked by another process then your query may wait for an extended period of time. Often times this is longer than the client has anticipated. Once the client has canceled then the DB transaction should exit as well. Right now, if the client cancels the database will _continue_ to wait until the query is able to execute. If you have many connections in and out then database will get backed up with queries that clients have already disconnected from.

**Comment by leebenson** [comment]
gotcha, that makes sense. Thanks for the explanation @blockloop.

**Comment by cmoad** [comment]
We are starting to investigate adding Context support. Today we use goqu to generate the sql and sqlx (with context) to actually execute the query. It would be far cleaner to just use goqu for the execution part as well. We have been protected by context in the past when users introduce new data that isn't yet performant. Our queries will stop executing after a defined time limit. Not allowing these queries to run effectively forever prevents the app from slowing to a crawl or exhausting memory.

**Comment by cmoad** [comment]
Opened #64 which adds context support.

**Comment by cmoad** [comment]
Can this issue be closed with the release of 5.0.0 which includes context support?
