### ISSUE TITLE
gopkg.in support

### ISSUE THREAD

**Issue by robertmeta** [doug-martin/goqu#6]
http://labix.org/gopkg.in -- do you plan on supporting gopkg.in?

**Comment by doug-martin** [comment]
This package is fairly young and I am waiting for some community use and feedback (to ensure there arent any major API changes) before I tag the current version as `v1`, once I do gopkg should support it based on the tag.

**Comment by doug-martin** [comment]
You can now install the package via `go get -u gopkg.in/doug-martin/goqu.v1`
