### ISSUE TITLE
Invalid statement which was generated ToSQL()

### ISSUE THREAD

**Issue by IhorBondartsov** [doug-martin/goqu#68]
main problem is using quotes in table name. If I use generated statement then MySQL will return Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near

**Comment by doug-martin** [comment]
I tried to reproduce this and the mysql dialect is properly escaping identifiers with a double and single quotes. 

Im guessing this is related to not registering the dialect properly.

```go
import (
        "fmt"
	"github.com/doug-martin/goqu/v7"
	_ "github.com/doug-martin/goqu/v7/dialect/mysql"
)

dialect := goqu.Dialect("mysql")

sql, _, _ := dialect.From("test").ToSQL()
fmt.Println(sql)
```
Output
```
SELECT * FROM `test`
```

Im closing this for now, if you can provide an example that demonstrates the error please reopen and Ill take a look.

**Comment by IhorBondartsov** [comment]
It was a long time ago!
