### ISSUE TITLE
Adapter Improvements

### ISSUE THREAD

**Issue by deitrix** [doug-martin/goqu#75]
When it comes to using goqu as a query builder only, without database handling, it's not trivial to create a dataset, using any of the non-default adapters. As far as I know, the only two options are:

option 1:
```go
database := goqu.New("mysql", nil)
dataset := database.From("table")
```

option 2:
```go
dataset := goqu.From("table")
dataset.SetAdapter(goqu.NewAdapter("mysql", dataset))
```

Nether of these is ideal.

There are a few options for improving this API.

option 1 - Change the function signature of NewAdapter so that it doesn't require a dataset be passed into it. This still isn't ideal, as I'd like to be able to call `goqu.From` without having to worry about dialects:

```go
dataset := goqu.From("table").SetAdapter("mysql")
```

option 2 - Allow for overriding of the default adapter. This kind of hinges on option 1 also being implemented, and then any subsequent calls to `goqu.From()` would use `goqu.DefaultAdapter`:

```go
goqu.DefaultAdapter = goqu.NewAdapter("mysql")
```

option 3 - goqu should recognise which of the adapters has been imported, and use that one. If no adapter is imported, use the default:

```go
import _ "gopkg.in/doug-martin/goqu.v5/adapters/mysql"

dataset := goqu.From("table")
```

**Comment by doug-martin** [comment]
@deitrix In `v7` I have added a new [`Dialect`](https://godoc.org/github.com/doug-martin/goqu#Dialect) method to address this very problem. When creating this we always used it in tandem with a Db but it seems people are using it just for sql generation. 

```go
import _ "github.com/doug-martin/goqu/v7/dialect/mysql"

dialect := goqu.Dialect("mysql")
ds := dialect.From("test").Where(goqu.Ex{
    "foo": "bar",
    "baz": []int64{1, 2, 3},
}).Limit(10)

sql, args, _ := ds.ToSQL()
fmt.Println(sql, args)

sql, args, _ = ds.Prepared(true).ToSQL()
fmt.Println(sql, args)
```
Output:
```
SELECT * FROM `test` WHERE ((`baz` IN (1, 2, 3)) AND (`foo` = 'bar')) LIMIT 10 []
SELECT * FROM `test` WHERE ((`baz` IN (?, ?, ?)) AND (`foo` = ?)) LIMIT ? [1 2 3 bar 10]
```

**Comment by deitrix** [comment]
Awesome. Thanks you!
