### ISSUE TITLE
Ability to specify insert columns when inserting from a select

### ISSUE THREAD

**Issue by deitrix** [doug-martin/goqu#76]
I can't find a way to generate the following insert statement:

```sql
INSERT INTO table (col1, col2, col3) SELECT col4, col5, col6 FROM other_table
```
Specifically the insert columns portion of the statement.

When running the following:
```go
insertDataset := goqu.From("other_table").Select("col4", "col5", "col6")

goqu.From("table").ToInsertSql(insertDataset)
```
The sql generated is:
```sql
INSERT INTO table SELECT col4, col5, col6 FROM other_table
```
Which only works in the case where the number of columns in `table` matches the number of columns in the select query. If `table` has columns other than `col1, col2, col3`, the query will fail because of a different number of value columns to table columns.

**Comment by wood-jp** [comment]
I have situation where the table columns match, because they are the same table. I'm having a hell of a time trying to write the code though. As from this stackoverflow answer: https://stackoverflow.com/a/18622851/2345647 the SQL I'm looking to replicate is this:

```
    INSERT INTO [OrganizationUnitHierarchy]
    (
        [AncestorId],
        [DescendantId],
        [Level]
    )
    SELECT [AncestorId], @NewChildId, [Level] + 1
    FROM [OrganizationUnitHierarchy]
    WHERE [DescendantId] = @ParentId
    UNION ALL
    SELECT @NewChildId, @NewChildId, 0
```
Also, I'm using Postgres rather than whatever this is.
How to write this with `goqu`? (Much thanks in advance)

**Comment by wood-jp** [comment]
Of course, as soon as I give up and ask, I figure it out:
```
insertDataset := goqu.From(closureTable).Select(
	goqu.L("ancestor_id, ?, depth + 1", newChildID),
).Where(
	goqu.I("descendant_id").Eq(parentID),
).UnionAll(
	goqu.From(closureTable).Select(
		goqu.L("?, ?, ?", newChildID, newChildID, 0),
	),
)
insert := goqu.From(closureTable).Insert(insertDataset)
```

**Comment by doug-martin** [comment]
This could be made a little easier Ill add this to the list of enhancements.

**Comment by doug-martin** [comment]
I have added this to `v8`. Ill close this issue once its merged.

```go
ds := goqu.Insert("user")
	Cols("first_name", "last_name").
	FromQuery(goqu.From("other_table").Select("fn", "ln"))
insertSQL, args, _ := ds.ToSQL()
fmt.Println(insertSQL, args)
```

Output: 
```
 INSERT INTO "user" ("first_name", "last_name") SELECT "fn", "ln" FROM "other_table" []
```
