### ISSUE TITLE
Inserting from select ignores ConflictExpression argument

### ISSUE THREAD

**Issue by deitrix** [doug-martin/goqu#77]
In file `dataset_insert.go:210`, the 2nd argument to InsertBeginSql should be a ConflictExpression. Instead, `nil` is being passed in.

```go
if err := me.adapter.InsertBeginSql(buf, nil); err != nil {
	return "", nil, err
}
```

This is preventing me from creating `INSERT IGNORE` queries when inserting from a select query.

**Comment by doug-martin** [comment]
@deitrix this should be fixed in `v7` take a look at https://github.com/doug-martin/goqu/blob/master/sql_dialect.go#L226 

Let me know if this doesn't completely address the issue you were experiencing.
