### ISSUE TITLE
Sqlite3 does not accept SELECT * UNION (SELECT *)

### ISSUE THREAD

**Issue by hellupline** [doug-martin/goqu#79]
Sqlite3 does not accept ```SELECT * UNION (SELECT *)```

the correct syntax should be ```SELECT * UNION SELECT *```

the same happens to ```INTERSECT``` and ```EXCEPT```

**Comment by hellupline** [comment]
I could not found where it add `(` and `)`, if you point me there, I could create a patch @doug-martin

**Comment by doug-martin** [comment]
Take a look at https://github.com/doug-martin/goqu/blob/master/default_adapter.go#L1084

You will most likely need to override that method for the sqlite adapter similar to how the mysql adapter creates its own adapter.
