### ISSUE TITLE
IdentifierExpression is reversed when calling Table after I

### ISSUE THREAD

**Issue by ssttevee** [doug-martin/goqu#88]
I've run into a bug where `I("table.column")` and `I("column").Table("table")` give different results in the final sql which is not the [documented behaviour](https://github.com/doug-martin/goqu/blob/8d01790421edba79339d046c7b836b30f39a915e/expressions.go#L624):

```
From("table").Select(I("table.column")) // SELECT "table"."column" FROM "table"
From("table").Select(I("column").Table("table")) // SELECT "column"."table" FROM "table"
```

Additionally:
```
I("table.column").GetTable() // table
I("table.column").GetCol() // column
I("table.column").GetSchema() // <blank>
I("column").Table("table").GetTable() // table
I("column").Table("table").GetCol() // <nil>
I("column").Table("table").GetSchema() // column
```

**Comment by doug-martin** [comment]
In the middle of a slight refactor, then Ill take a look at this.

**Comment by doug-martin** [comment]
Hi @ssttevee in the new version of `goqu` I made a few changes that should make this a little more clear. I have added three new methods:

* [`S(schema string)`](https://godoc.org/github.com/doug-martin/goqu#S) - This will create a new identifier with the schema set
* [`T(table string)`](https://godoc.org/github.com/doug-martin/goqu#T) - This will create a new identifier with the table set
* [`C(col string)`](https://godoc.org/github.com/doug-martin/goqu#C) - This will create a new identifier with the column set.

[`I(iden string)`](https://godoc.org/github.com/doug-martin/goqu#I) still exists but it is primarily used for parsing an identifier that is seperated by a `.` character, if you have a specific part of an Identifier (Schema, Table or Col) you should use one of the new methods to be more explicit about which part you are using. 

Your example above could change to the following
```go
From("table").Select(I("table.column")) // SELECT "table"."column" FROM "table"
From("table").Select(C("column").Table("table")) // SELECT "table"."column" FROM "table"

//or 
t := T("table")
From(t).Select(t.Col("column")) // SELECT "table"."column" FROM "table"
```
Hope this helps!

**Comment by deitrix** [comment]
@doug-martin Given the changes introduced in 7.0.0 to how identifiers are constructed (`goqu.S`, `goqu.T` and `goqu.C`), this can probably be closed.

**Comment by doug-martin** [comment]
> @doug-martin Given the changes introduced in 7.0.0 to how identifiers are constructed (`goqu.S`, `goqu.T` and `goqu.C`), this can probably be closed.

Haha yep seems we commented at the same time!

**Comment by deitrix** [comment]
@doug-martin Nice! What are the odds? 😆
