### ISSUE TITLE
Can't scan values using []byte or []string

### ISSUE THREAD

**Issue by ssttevee** [doug-martin/goqu#90]
Using postgres,

```
var data []byte
db.From("table").Select("data").ScanVal(&data)
```

The above snippet fails with this error:

```
goqu: Cannot scan into a slice when calling ScanVal
```

I can work around this by wrapping it in a container type and using `ScanStruct` instead of `ScanVal`:

```
var container struct {
	Data []byte `db:"data"`
}

db.From("table").Select("data").ScanStruct(&container)

data := container.data
```

The same thing happens with `pq.StringArray` (and `[]string`) even though it implements `sql.Scanner`.

**Comment by doug-martin** [comment]
Fixed in the latest version
