### ISSUE TITLE
Manually modifying queries before execution (v7)

### ISSUE THREAD

**Issue by ssttevee** [doug-martin/goqu#93]
With v6, using `CrudExec`, I was able to modify the queries before executing them using the exposed `Sql` field. I am using it with extra features of postgres like [`UPSERT`](https://wiki.postgresql.org/wiki/UPSERT) and [`INSERT ... RETURNING`](https://www.postgresql.org/docs/current/sql-insert.html).

It doesn't look like that's possible with the new `exec.QueryExecutor` api.

Please consider exposing its [`query`](https://github.com/doug-martin/goqu/blob/b539688da07689e0813aef5627dcd3d91739d35c/exec/query_executor.go#L16) field.

**Comment by doug-martin** [comment]
Out of curiosity could you provide an example or two of exactly how you are modifying them?

**Comment by ssttevee** [comment]
```
func Upsert(exec *goqu.CrudExec) *goqu.CrudExec {
	exec.Sql = "UP" + exec.Sql[2:] // change "INSERT" into "UPSERT"
	return exec
}
```
```
func InsertReturning(dataset *goqu.Dataset, data interface{}, identifiers ...interface{}) *goqu.CrudExec {
	builder := goqu.NewSqlBuilder(true)
	if err := dataset.Adapter().Literal(builder, goqu.L(strings.Repeat(",?", len(identifiers))[1:], identifiers...)); err != nil {
		panic(err)
	}

	exec := dataset.Insert(data)
	if len(identifiers) > 0 {
		exec.Sql += " RETURNING " + builder.String()
	}

	return exec
}
```

**Comment by ssttevee** [comment]
I realize now that there's a `Returning` function on `Dataset` :|

**Comment by doug-martin** [comment]
Insert on conflict is also supported see https://github.com/doug-martin/goqu/blob/master/dialect/postgres/postgres_test.go#L342. I'll enhance the docs for that.

Will both of those solve your needs? I'll have to do more than expose the query to support your use case and I'm hesitant to leak some of the internals out like that.

**Comment by ssttevee** [comment]
I'm using `UPSERT` instead of `INSERT ON CONFLICT` because the input data is coming from a subquery, and to use the latter, it seems like I'll have to duplicate the subquery.

I'm trying to work on a solution using `ToInsertSQL` instead.

**Comment by ssttevee** [comment]
I think I'm able to get away with directly using `exec.QueryFactory` with something like this:

```
sql, args, _ := db.From("table").ToInsertSQL(records)
sql = "UP" + sql[2:]
exec.NewQueryFactory(db).FromSQL(sql, args...)
```
